name: Zip it up
on:
  push:
jobs:
  build-lnx:
    name: Linux
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: | 
        sudo apt install p7zip

    - name: Pack things up
      id: pack
      run: | 
        7z a "sphinx-blender-tools-$(date +%Y.%m.%d-%H.%M -u).zip" io_scene_sphnx

    - name: Upload Release Asset
      id: upload-release-asset
      env:
        GITHUB_TOKEN: ${{ secrets.TK }}
      run: |
        owner="Swyter"
        repo="sphinx-euroland"
        release_id="32423809"
        
        FILENAME="$(find . -name '*tools*.zip' | sort -r -u | head -n 1)"
        GH_ASSET="https://uploads.github.com/repos/$owner/$repo/releases/$release_id/assets?name=$FILENAME"
        
        echo "$GH_ASSET"; echo "$FILENAME"
        curl --data-binary @"$FILENAME" -H "Authorization: token $GITHUB_TOKEN" -H "Content-Type: application/octet-stream" "$GH_ASSET"
